/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.is.sirentcam.view;

import javax.swing.JOptionPane;
import org.is.sirentcam.model.User;
import org.is.sirentcam.servicedbimpl.ControllerLogin;

/**
 *
 * @author Nazril
 */
public class Registrasi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registrasi.class.getName());

	ControllerLogin conlogin = new ControllerLogin();
	
    /**
     * Creates new form Registrasi
     */
    public Registrasi() {
        initComponents();
		this.setLocationRelativeTo(null);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbShowPass = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsernameRegist = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPasswordRegist = new javax.swing.JPasswordField();
        btnRegist = new javax.swing.JButton();
        cbShowPassRegist = new javax.swing.JCheckBox();
        btnRegist1 = new javax.swing.JLabel();

        cbShowPass.setForeground(new java.awt.Color(0, 0, 0));
        cbShowPass.setText("show password");
        cbShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPassActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REGISTER");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Username");

        txtUsernameRegist.setBackground(new java.awt.Color(204, 204, 204));
        txtUsernameRegist.setForeground(new java.awt.Color(0, 0, 0));
        txtUsernameRegist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameRegistActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password");

        txtPasswordRegist.setBackground(new java.awt.Color(204, 204, 204));
        txtPasswordRegist.setForeground(new java.awt.Color(0, 0, 0));
        txtPasswordRegist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordRegistKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordRegistKeyTyped(evt);
            }
        });

        btnRegist.setBackground(new java.awt.Color(204, 204, 204));
        btnRegist.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegist.setForeground(new java.awt.Color(0, 0, 0));
        btnRegist.setText("REGISTRASI");
        btnRegist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistActionPerformed(evt);
            }
        });

        cbShowPassRegist.setForeground(new java.awt.Color(0, 0, 0));
        cbShowPassRegist.setText("show password");
        cbShowPassRegist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPassRegistActionPerformed(evt);
            }
        });

        btnRegist1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRegist1.setForeground(new java.awt.Color(0, 0, 0));
        btnRegist1.setText("sudah punya akun? silahkan login");
        btnRegist1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegist1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegist1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegist1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(btnRegist)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPasswordRegist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(txtUsernameRegist, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbShowPassRegist)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtUsernameRegist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtPasswordRegist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbShowPassRegist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegist)
                    .addComponent(btnRegist1))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void clearData() {
		txtUsernameRegist.setText("");
	}
	
    private void txtUsernameRegistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameRegistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameRegistActionPerformed

    private void cbShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbShowPassActionPerformed

    private void btnRegistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistActionPerformed
        // TODO add your handling code here:
		String username = txtUsernameRegist.getText();
		String password = txtPasswordRegist.getText();
		
		if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username dan Password tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
		
		User user = new User(username, password);
		boolean registStatus = conlogin.regist(user);
		
		if (registStatus) {
			JOptionPane.showMessageDialog(this, "Registrasi Berhasil! Silakan Login.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            txtUsernameRegist.setText("");
            txtPasswordRegist.setText("");
		}else{
			JOptionPane.showMessageDialog(this, "Registrasi Gagal! Username mungkin sudah digunakan.", "Error", JOptionPane.ERROR_MESSAGE);
		}
		
    }//GEN-LAST:event_btnRegistActionPerformed

    private void cbShowPassRegistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPassRegistActionPerformed

        if (cbShowPassRegist.isSelected()) {
            txtPasswordRegist.setEchoChar((char)0);
        } else {
            txtPasswordRegist.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_cbShowPassRegistActionPerformed

    private void txtPasswordRegistKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordRegistKeyTyped
        // TODO add your handling code here:
		
    }//GEN-LAST:event_txtPasswordRegistKeyTyped

    private void txtPasswordRegistKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordRegistKeyPressed
        // TODO add your handling code here:
		String username = txtUsernameRegist.getText();

        try {

            if (username.equals("")) {
                JOptionPane.showMessageDialog(null, "Masukan username terlebih dahulu!", "Peringatan",JOptionPane.WARNING_MESSAGE);
                clearData();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Sistem sedang gangguan!");
        }
    }//GEN-LAST:event_txtPasswordRegistKeyPressed

    private void btnRegist1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegist1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnRegist1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registrasi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegist;
    private javax.swing.JLabel btnRegist1;
    private javax.swing.JCheckBox cbShowPass;
    private javax.swing.JCheckBox cbShowPassRegist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPasswordRegist;
    private javax.swing.JTextField txtUsernameRegist;
    // End of variables declaration//GEN-END:variables


}
